"""added uniqueness to deck name

Revision ID: 0fe7b26263f9
Revises: f5ef659ca024
Create Date: 2024-01-27 18:56:53.573364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe7b26263f9'
down_revision = 'f5ef659ca024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_decks_name'), ['name'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')

    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_decks_name'), type_='unique')

    # ### end Alembic commands ###
