"""delete uniqueness from deck

Revision ID: 1fbdc2153178
Revises: 0fe7b26263f9
Create Date: 2024-01-30 21:05:06.767579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbdc2153178'
down_revision = '0fe7b26263f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_decks_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_decks_name', ['name'])

    # ### end Alembic commands ###
